Iter18
AlexTerra21/shortener pull request #21
Opened 2024-03-31 07:02 UTC by AlexTerra21

2024-04-04 20:20 UTC, bambruysk requested changes
Нет профилей и где была сделана оптимизация?

2024-04-04 20:20 UTC, bambruysk commented on internal/app/storage/storagers/db_test.go
> +	})
Это не точная история 

Нужно использовать цикл с b.N  итерациями
сейчас измеряется время запуска которое 1000 ( это хардкод) 

количество прогонов задается через флаги `go test`

2024-04-05 16:27 UTC, AlexTerra21 commented on internal/app/storage/storagers/db_test.go
> +	})
Исправлено

2024-04-06 07:39 UTC, bambruysk approved these changes
принято

2024-04-08 06:04 UTC, merged